export const allMentors = [
        {
                id: "1",
                first_name: "Jane",
                last_name: "Doe",
                phone: "0400 000 454",
                email: "jane.doe@gmail.com",
                city: "Perth",
                skills: "HTML",
                will_travel: true,
                payment_type: "Mentor give back" ,
                junior_mentor: true,
                industry_mentor: false,
                lead_mentor: false,
                she_codes_alumni: false,
                current_step: "Step 7 - Mentoring",
                notes: "",
                feedback: "",
                is_active: true, 
            },
            {
                id: "2",
                first_name: "Mark",
                last_name: "Smith",
                phone: "0404 333 666",
                email: "mark.smith@hotmail.com",
                city: "Brisbane",
                skills: "HTML, CSS, JavaScript",
                will_travel: false,
                payment_type: "Volunteer" ,
                junior_mentor: false,
                industry_mentor: false,
                lead_mentor: true,
                she_codes_alumni: true,
                current_step: "Step 1 - Interview",
                notes: "",
                feedback: "",
                is_active: true,
    
            }
        ]